name: Build and Test Ros Packages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          distribution: humble

      - name: build and run
        run: |
          mkdir -p ros2_ws/src
          # Symlink package if it's not already in src
          ln -s $GITHUB_WORKSPACE ros2_ws/src/your_package_name
          cd ros2_ws
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+
          ls

      - name: Test
        run: |
          cd ros2_ws
          source install/setup.bash
          colcon test
          colcon test-result --verbose
