name: Build and Test ROS Packages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          distribution: humble

      - name: Build and Test
        shell: bash
        run: |
          set -e

          echo "Setting up workspace..."
          mkdir -p ros2_ws/src
          
          echo "Linking package into workspace..."
          PACKAGE_NAME=$(basename "$GITHUB_WORKSPACE")
          ln -sfn "$GITHUB_WORKSPACE" "ros2_ws/src/$PACKAGE_NAME"

          echo "Installing dependencies..."
          cd ros2_ws
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

          ls
          echo "Building packages..."
          cd src
          ls
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+
          ls

          echo "Running tests..."
          source install/setup.bash
          colcon test
          colcon test-result --verbose
