name: Build and Test ROS Packages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble  # ✅ Corrected key

      - name: Build Colcon Workspace
        shell: bash
        run: |
          set -e
          
          # Source ROS 2 setup
          source /opt/ros/humble/setup.bash

          echo "Setting up workspace..."
          mkdir -p ros2_ws/src

          echo "Getting package name from repository..."
          PACKAGE_NAME=$(basename "$GITHUB_WORKSPACE")
          echo "Package name: $PACKAGE_NAME"

          echo "Linking package into workspace..."
          ln -sfn "$GITHUB_WORKSPACE" "ros2_ws/src/$PACKAGE_NAME"

          cd ros2_ws

          echo "Installing ROS 2 dependencies..."
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

          echo "Building the workspace..."
          colcon build
          
      - name: Run and Test
        shell: bash
        run: |
          set -e
          cd ros2_ws
          source install/setup.bash
          colcon test
          colcon test-result --verbose
